<?php

/**
 * @file
 * Add ARIA landmark roles to Drupal blocks.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function block_aria_landmark_roles_form_block_form_alter(&$form, FormStateInterface $form_state) {
  /** @var Block $block */
  $block = $form_state->getFormObject()->getEntity();

  $form['third_party_settings']['#tree'] = TRUE;

  $form['third_party_settings']['block_aria_landmark_roles']['role'] = [
    '#title' => t('ARIA landmark role'),
    '#description' => t('Add a landmark role to this block.'),
    '#type' => 'select',
    '#options' => ['' => t('- None -')] + _block_aria_landmark_roles_get_roles(),
    '#default_value' => $block->getThirdPartySetting('block_aria_landmark_roles', 'roles'),
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function block_aria_landmark_roles_preprocess_block(&$variables) {
  if (!empty($variables['elements']['#id'])) {
    $block = Block::load($variables['elements']['#id']);

    if ($role = $block->getThirdPartySetting('block_aria_landmark_roles', 'role')) {
      $variables['attributes']['role'] = $role;
    }
  }
}

/**
 * Return a list ARIA roles.
 *
 * @param bool $associative
 *   (optional) Whether to return an associative array. Defaults to TRUE.
 *
 * @return array
 */
function _block_aria_landmark_roles_get_roles($associative = TRUE) {
  $roles = [
    'banner',
    'complementary',
    'contentinfo',
    'main',
    'navigation',
    'search',
  ];

  return $associative ? array_combine($roles, $roles) : $roles;
}
