<?php

/**
 * @file
 * Adds additional elements on block administration forms to add ARIA landmark roles.
 */

/**
 * Implementation of hook_form_alter().
 *
 * Adds additional elements to the 'add block' and 'configure block' forms.
 */
function block_aria_landmark_roles_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'block_add_block_form' || $form_id == 'block_admin_configure') {
    // Build the block object.
    $block = new stdClass;
    $block->module = $form['module']['#value'];
    $block->delta = $form['delta']['#value'];
    
    // Create the additional form elements.
    $form['block_aria_role'] = array(
      '#title' => t('Block ARIA Landmark Role settings'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#weight' => 0,
    );
    $form['block_aria_role']['aria_role'] = array(
      '#title' => t('ARIA Landmark Role'),
      '#description' => t('Specify a ARIA landmark role to add to this block.'),
      '#type' => 'textfield',
      '#default_value' => block_aria_landmark_roles_get_role($block),
    );
    
    // Add extra submission function.
    $form['#validate'][] = 'block_aria_landmark_roles_form_validate'; 
    $form['#submit'][] = 'block_aria_landmark_roles_form_submit';
  }
}

/**
 * Form validation handler for the ARIA landmark role.
 *
 * Ensures that the ARIA landmark role is valid.
 */
function block_aria_landmark_roles_form_validate($form, &$form_state) {
  if (!empty($form_state['values']['aria_role'])) {
    // Confirm that the entered role is valid.
    $valid_roles = array('banner', 'navigation', 'search', 'main', 'complementary', 'contentinfo');
    if (!in_array($form_state['values']['aria_role'], $valid_roles)) {
      form_set_error('aria_role', t('%role is not a valid ARIA landmark role.', array('%role' => $form_state['values']['aria_role'])));
    }
  }
}

/**
 * Form submission handler for the ARIA landmark role.
 *
 * Saves the data to the block_aria_landmark_roles table.
 */
function block_aria_landmark_roles_form_submit($form, &$form_state) {
  if (isset($form_state['values']['aria_role']) && user_access('administer blocks')) {
    $module = $form_state['values']['module'];
    $delta = $form_state['values']['delta'];
    $role = $form_state['values']['aria_role'];
    
    // Delete any existing role.
    db_query("DELETE FROM {block_aria_landmark_roles} WHERE module = '%s' AND delta = '%s'", $module, $delta);
    
    // Save the new role.
    if (!empty($form_state['values']['aria_role'])) {
      $record = new stdClass;
      $record->module = $module;
      $record->delta = $delta;
      $record->aria_role = $role;
      drupal_write_record('block_aria_landmark_roles', $record);
    }
  }
}

/**
 * Find an ARIA landmark role for a certain block.
 *
 * @param obj $block
 *  An object containing the name of the module and the delta of the block.
 *
 * @return string|bool
 *  Returns the role if one was found. If not, returns nothing.
 */
function block_aria_landmark_roles_get_role($block) {
  $role = db_result(db_query("SELECT aria_role FROM {block_aria_landmark_roles} WHERE module = '%s' AND delta = '%s'", $block->module, $block->delta));
  return $role ? $role : '';
}

/**
 * Implementation of hook_preprocess_HOOK().
 */
function block_aria_landmark_roles_preprocess_block(&$variables) {
  $block = (object) array(
    'module' => $variables['block']->module,
    'delta' => $variables['block']->delta,
  );
  $role = block_aria_landmark_roles_get_role($block);
  $variables['aria_role'] = ($role) ? 'role="' . $role . '"' : NULL;
}